### ISSUE TITLE
Crash when right clicking raspberry bushes

### ISSUE THREAD

**Issue by KuroNeko87** [gabriella-campos-davis/Herbarium#1]
Running on 64 bit Windows with 65371 MB RAM
Game Version: v1.18.15 (Stable)
10/24/2023 7:33:45 PM: Critical error occurred in the following mod: herbarium@1.0.0
Loaded Mods: aculinaryartillery@1.0.15, bandedgeckos@1.2.0, betterruins@0.2.4, bettertraders@0.0.2, hqzlights@1.1.1, driedpeat@1.0.3, fantasycreatures@0.6.4, morecrops@1.0.3, TA_fieldsandplateaus@1.0.2, fieldsofgold@2.1.6, caninae@1.0.4, capreolinae@1.0.5, pantherinae@1.0.8, furniturelibrary@1.0.9, HangingOilLamps@1.0.1, hideandfabric@1.3.0, instruments@1.2.2, morecaveart@1.0.0, moremolds@1.4.2, nasalamanders@1.0.0, natshumanskin@1.0.0, pondfrogsiii@1.2.3, pondfrogsi@1.2.3, OrnamentalFish@3.0.0, pacificnewts@1.3.0, palisademod@1.1.0, peacockbasses@1.1.1, primitivesurvival@3.3.0, spidersilk@1.2.2, ssppvv@1.0.5, litbrig@0.5.0, truesunfishes@1.1.1, viescraftmachines@2.2.2, game@1.18.15, weaponpackalphaunoff@1.4.0, wildcrafttrees@1.2.4, wildcraft@1.6.6, additionalmolds@1.0.1, alchemy@1.6.16, ancienttools@1.5.9, animalcages@2.2.0, bonfires@0.2.1, carryon@1.6.0, chickenSit@2.0.0, expandedfoods@1.6.8, fishing@1.1.5, forlornhope@0.0.4, herbarium@1.0.0, hudclock@3.3.0, sailboat@1.1.0, lichen@1.6.2, medievalexpansion@3.11.1, morebags@1.2.0, morepiles@1.4.3, petai@1.8.1, roadworks@1.0.9, rustboundmagic@0.2.5, storageoptions@1.0.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, woodbarrels@1.0.4, woodchests@1.1.0, woodfp@1.0.0, airtightsleekdoors@1.0.0, bugnetcompatibility@1.0.1, bullseye@2.5.0, cats@1.8.0, em@2.4.1, feverstonehorses@1.5.0, feverstonewilds@1.4.3, sleekdoorglass@1.0.0, simplewinddirection@1.0.2, wildcraftfruit@1.0.0, wolftaming@1.8.0, bricklayers@2.4.0, moreroads@1.5.4
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain) in VintagestoryApi\Common\Assets\AssetLocation.cs:line 196
   at herbarium.HerbariumBerryBush.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in D:\VSMods\Herbarium\Herbarium\src\Block\HerbariumBerryBush.cs:line 34
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 867
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 10/24/2023 7:30:04 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER7592.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_e8febbbb-c048-44f1-b08e-44c14088f0cc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5904d790-66eb-440f-9a2f-91ae412a1170
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/24/2023 7:30:03 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_e8febbbb-c048-44f1-b08e-44c14088f0cc

Analysis symbol: 
Rechecking for solution: 0
Report Id: 5904d790-66eb-440f-9a2f-91ae412a1170
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 10/24/2023 7:30:01 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0xe848
Faulting application start time: 0x01da06c7594e1dfa
Faulting application path: C:\Users\Romanov\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\Romanov\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 5904d790-66eb-440f-9a2f-91ae412a1170
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by campbebj** [comment]
i also get this with dogrose hips

**Comment by Matiam0** [comment]
Getting the same crash case, it is specifically rasberry bushes.

[Log Here](https://pastebin.com/qREJSG1D)

**Comment by gabriella-campos-davis** [comment]
thank you all for responding. Wildcraft: Fruits & Nuts along with Herbarium is not compatible with the old version of Wildcraft, i apologize for any confusion. the incompatability between the the old version and the new version is likely causing the crashes.
