### ISSUE TITLE
Husk tomato clippings Server hang

### ISSUE THREAD

**Issue by CypressBz** [gabriella-campos-davis/Herbarium#2]
Plant husk tomato clipping, results in constant console spam 

Only way to fix is to disable mod, remove offending missing object blocks, and then re-enable the mods. Results in any bushes loaded without the mod to stop functioning or progressing in growth.

`27.10.2023 21:07:18 [Fatal] System.ArgumentNullException: BEClipping newBushBlock is Null. Exiting. (Parameter 'newBushBlock')
at herbarium.BEClipping.DoGrow(String state) in D:\VSMods\Herbarium\Herbarium\src\BlockEntity\BEClipping.cs:line 107
at herbarium.BEClipping.CheckGrow(Single dt) in D:\VSMods\Herbarium\Herbarium\src\BlockEntity\BEClipping.cs:line 97
at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\EventManager.cs:line 59
at Vintagestory.Server.CoreServerEventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerEventManager.cs:line 124
at Vintagestory.Server.ServerMain.Process() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\ServerMain.cs:line 881`

**Comment by gabriella-campos-davis** [comment]
thanks for the report, Herbarium 1.0.1 may have helped this issue, but i'm going to leave this open until i can actually confirm that

**Comment by gabriella-campos-davis** [comment]
I'm marking this as close unless you want to provide more info about your world and what mods were being used
