### ISSUE TITLE
Crashing on Berry Harvest on Modded Vintage Story - Vanilla Bushes

### ISSUE THREAD

**Issue by TiredGamerSyndrome** [gabriella-campos-davis/Herbarium#3]
Running on 64 bit Windows with 65429 MB RAM
EMTK Version: 3.0.5
Game Version: v1.18.15 (Stable)
12/30/2023 5:44:41 PM: Critical error occurred in the following mod: herbarium@1.0.1
Loaded Mods: game@1.18.15, wildcrafttrees@1.2.4, wildcraft@1.6.6, herbarium@1.0.1, creative@1.18.15, survival@1.18.15, wildfarmingrevival@1.1.6, wildcraftfruit@1.0.1
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain) in VintagestoryApi\Common\Assets\AssetLocation.cs:line 196
   at herbarium.HerbariumBerryBush.OnBlockInteractStart(IWorldAccessor world, IPlayer byPlayer, BlockSelection blockSel) in D:\VSMods\Herbarium\Herbarium\src\Block\HerbariumBerryBush.cs:line 34
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseBlock(Block selectedBlock, BlockSelection blockSelection) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 867
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 447
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 92
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 790
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 983
   at Vintagestory.Client.ScreenManager.Render_Patch0(ScreenManager this, Single dt)
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 12/29/2023 7:14:41 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket 2007150627803250050, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e30a3141-a71c-40b5-823b-9ee9c43e7dc0.tmp.WERInternalMetadata.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_f1970062-f8a9-48ff-9291-a4b8d2a328fa

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b3f0634-325f-4fba-877d-e2b7cd4971cb
Report Status: 268566528
Hashed bucket: 38dd2bbe130a69d3fbdad4dc94ea3d82
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/29/2023 7:14:40 PM, Site = , Source = Windows Error Reporting, Message = Fault bucket , type 0
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.18.15.0
P3: 64e841c5
P4: openal32.dll
P5: 1.23.0.0
P6: 63dd31ad
P7: 40000015
P8: 00000000000df046
P9: 
P10: 

Attached files:

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_Vintagestory.exe_3278c09e339ad58fdb4a48929ddf95e5f2060ca_ee8069fc_f1970062-f8a9-48ff-9291-a4b8d2a328fa

Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b3f0634-325f-4fba-877d-e2b7cd4971cb
Report Status: 131076
Hashed bucket: 
Cab Guid: 0 }
--------------
{ TimeGenerated = 12/29/2023 7:14:39 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.15.0, time stamp: 0x64e841c5
Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
Exception code: 0x40000015
Fault offset: 0x00000000000df046
Faulting process id: 0x0xde98
Faulting application start time: 0x0x1da3ace353250a5
Faulting application path: C:\Users\#####\AppData\Roaming\Vintagestory\Vintagestory.exe
Faulting module path: C:\Users\#####\AppData\Roaming\Vintagestory\Lib\openal32.dll
Report Id: 1b3f0634-325f-4fba-877d-e2b7cd4971cb
Faulting package full name: 
Faulting package-relative application ID:  }

**Comment by TiredGamerSyndrome** [comment]
Did another run with less mods focusing just on Wildcraft

**Comment by gabriella-campos-davis** [comment]
You were using both Wildcraft alongside Herbarium and the new fruit module, which is what was causing the crash.
