### ISSUE TITLE
NullReferenceException (1.19.3 mp)

### ISSUE THREAD

**Issue by WickedSchnitzel** [gabriella-campos-davis/Herbarium#5]
[Server Worldgen] An error was thrown in pass Vegetation when generating chunk column X=1964,Z=2258 in world 'CoB19' with seed 739509137
Exception System.NullReferenceException: Object reference not set to an instance of an object.
   at herbarium.HerbariumBerryBush.CanPlantStay(IBlockAccessor blockAccessor, BlockPos pos) in D:\VSMods\Herbarium\Herbarium\src\Block\HerbariumBerryBush.cs:line 98
   at Vintagestory.GameContent.BlockPlant.TryPlaceBlockForWorldGen(IBlockAccessor blockAccessor, BlockPos pos, BlockFacing onBlockFace, LCGRandom worldGenRand) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Block\BlockPlant.cs:line 170
   at Vintagestory.ServerMods.NoObf.BlockPatch.Generate(IBlockAccessor blockAccessor, LCGRandom rnd, Int32 posX, Int32 posY, Int32 posZ, Int32 firstBlockId) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\8.GenVegetationAndPatches\BlockPatch.cs:line 169
   at Vintagestory.ServerMods.GenVegetationAndPatches.genPatches(Int32 chunkX, Int32 chunkZ, Boolean postPass) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\8.GenVegetationAndPatches\GenVegetationAndPatches.cs:line 226
   at Vintagestory.ServerMods.GenVegetationAndPatches.OnChunkColumnGen(IChunkColumnGenerateRequest request) in C:\Users\Tyron\Documents\vintagestory\game\VSSurvivalMod\Systems\WorldGen\Standard\ChunkGen\8.GenVegetationAndPatches\GenVegetationAndPatches.cs:line 162
   at Vintagestory.Server.ServerSystemSupplyChunks.runGenerators(ChunkColumnLoadRequest chunkRequest, Int32 forPass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Server\Systems\World\LoadThread\SupplyChunks.cs:line 1725

**Comment by gabriella-campos-davis** [comment]
What version of Herbarium was being used?

**Comment by WickedSchnitzel** [comment]
Still getting log spam with 

24.3.2024 06:56:40 [Error] At position 68989, 203, 104342 for block bigberrybush-redcurrant-flowering a BETallBerryBush threw an error when ticked:
24.3.2024 06:56:40 [Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.AssetLocation.Create(String domainAndPath, String defaultDomain) in VintagestoryApi\Common\Assets\AssetLocation.cs:line 197
   at herbarium.BETallBerryBush.DoGrow() in D:\VSMods\Herbarium\Herbarium\src\BlockEntity\BETallBerryBush.cs:line 227
   at herbarium.BETallBerryBush.CheckGrow(Single dt) in D:\VSMods\Herbarium\Herbarium\src\BlockEntity\BETallBerryBush.cs:line 86
   at Vintagestory.Common.GameTickListener.OnTriggered(Int64 ellapsedMilliseconds) in VintagestoryLib\Common\Model\GameTickListener.cs:line 27
   
   in 1.19.5 stable

**Comment by WickedSchnitzel** [comment]
plus many question mark blocks everywhere. like on top of bushes (the clippings?)
