### ISSUE TITLE
Chopping mod wood with resin causes client disconnect/crash from server

### ISSUE THREAD

**Issue by RogueRaiden** [gabriella-campos-davis/Herbarium#7]
player gets booted from server when trying to chop a modded tree wood (Wildcraft Trees and Shrubs module) with a resin in the tree. if you chop above the resin, it will cut down the above logs. i think harvesting the resin also allows cutting of the tree

`28.4.2024 13:08:09 [Server Event] Player RinkoTinko got removed. Reason: Threw an exception at the server
28.4.2024 13:08:09 [Server Error] Exception: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.Block.OnBlockBroken_Patch1(Block this, IWorldAccessor world, BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier)
   at Vintagestory.Common.BlockAccessorBase.BreakBlock(BlockPos pos, IPlayer byPlayer, Single dropQuantityMultiplier) in VintagestoryLib\Common\API\BlockAccessorBase.cs:line 548
   at Vintagestory.GameContent.ItemAxe.OnBlockBrokenWith_Patch1(ItemAxe this, IWorldAccessor world, Entity byEntity, ItemSlot itemslot, BlockSelection blockSel, Single dropQuantityMultiplier)
   at Vintagestory.Server.ServerSystemBlockSimulation.TryModifyBlockInWorld(ServerPlayer player, Packet_ClientBlockPlaceOrBreak cmd) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 575
   at Vintagestory.Server.ServerSystemBlockSimulation.HandleBlockPlaceOrBreak(Packet_Client packet, ConnectedClient client) in VintagestoryLib\Server\Systems\World\BlockSimulation.cs:line 346
   at Vintagestory.Server.ServerMain.ProcessNetMessage(NetIncomingMessage msg, NetServer mainSocket) in VintagestoryLib\Server\ServerMainNetworking.cs:line 138`

**Comment by gabriella-campos-davis** [comment]
very weird, i'll try and look into this. do you happen to be using any other mods?

**Comment by RogueRaiden** [comment]
Oh yeah, there are a few.

Most notibly that might touch resin or trees... Ancient Tools, A Culinary Artillery, XSkills, DanaTweaks

**Comment by RogueRaiden** [comment]
DanaTweaks has a "drop resin anyway" feature, perhaps that is interacting and causing the crash with modded woods containing resin

**Comment by gabriella-campos-davis** [comment]
I'm not certain, but it's very likely one of those mods causing the issue. I know we don't yet have compatibility with Ancient Tools (it's on my to-do list), but the "drop resin anyways" feature also seems like a likely crash causing culprit.
